[package]
name = "client"
version = "0.1.0"
authors = ["Raphael Matile <raphael.matile@gmail.com>"]

[dependencies]
log = "0.4"
simple_logger = "0.5"
node = { git = "https://github.com/provotum/node", branch = "master"}
